apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 886436962423.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:18
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://k8s-threetie-frontend-c843bf4b63-545580554.ap-southeast-1.elb.amazonaws.com/api/tasks"  ##(update alb dns manually and recreate frontend image)
            ##(in realworld route53 url is used in place on albdns)
        ports:
        - containerPort: 3000
